# Generated by Django 2.1.7 on 2019-04-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.TextField()),
                ('price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movietreu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.TextField()),
                ('content', models.TextField()),
                ('actor', models.CharField(max_length=20)),
                ('imgsrc', models.TextField()),
            ],
            options={
                'db_table': 'movietreu',
                'managed': True,
            },
        ),
    ]
